# Generated by Django 4.2 on 2024-03-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_identifier', models.CharField(max_length=10)),
                ('event_name', models.CharField(max_length=60)),
                ('severity', models.CharField(max_length=10)),
                ('occurrence_time', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Latitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('position', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Longitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('position', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
